### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bigtreeshen** [gforge/criterion_ignore#1]
Hi gforge,

Thanks for sharing your code! I got a problem here when I try to install your module with luarocks install. I got problem like this:
`Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/gforge/criterion_ignore/master/criterion_ignore-0.2-1.rockspec - criterion_ignore-0.2-1.rockspec`

Am I doing anything wrong?

**Comment by gforge** [comment]
How did you try to install it? You can see in my Docker-file the full command that has worked so far for me: https://github.com/gforge/Gocker/blob/master/Torch/Dockerfile_nnx.template#L18

**Comment by bigtreeshen** [comment]
@gforge Thanks for the guide, it has been installed sucessfully!
